// Pure presentation layer for the Phase 3 pricing/comparison UI. Every
// number here is DERIVED from the existing metering and payments config —
// this file must never hardcode a plan limit, a rupee amount, or a window
// duration. That is what keeps marketing copy from drifting out of sync
// with what the backend actually enforces.
import {
  PLAN_LIMITS,
  PLAN_NAMES,
  USAGE_ACTION_TYPES,
  USAGE_WINDOW_MS,
  type MeteredUsageAction,
  type PlanName,
} from '../usage/config';
import {
  PAID_PLANS,
  PLAN_ACCESS_DAYS_DEFAULT,
  PLAN_PRICING_PAISE,
  isPaidPlan,
  launchAmountFor,
  listAmountFor,
  type PaidPlan,
} from './config';

// Intentionally re-exported so callers never need to import from both
// usage/config and payments/config to build a plan-aware UI.
export { PLAN_NAMES, PAID_PLANS, isPaidPlan };
export type { PlanName, PaidPlan, MeteredUsageAction };

const INR_FORMATTER = new Intl.NumberFormat('en-IN', {
  style: 'currency',
  currency: 'INR',
  maximumFractionDigits: 0,
});

export function formatInr(paise: number): string {
  return INR_FORMATTER.format(paise / 100);
}

export const USAGE_WINDOW_HOURS = USAGE_WINDOW_MS / (60 * 60 * 1000);

// e.g. "per rolling 12-hour window"
export const USAGE_WINDOW_LABEL = `per rolling ${USAGE_WINDOW_HOURS}-hour window`;

// e.g. "One-time payment · 30 days access · No auto-renewal"
export const ACCESS_TERMS_LABEL = `One-time payment · ${PLAN_ACCESS_DAYS_DEFAULT} days access · No auto-renewal`;

export type PlanBadge = 'Most popular' | null;

export interface PlanCard {
  plan: PlanName;
  isPaid: boolean;
  priceLabel: string;
  listPriceLabel: string | null;
  badge: PlanBadge;
  accessDays: number | null;
  limits: Record<MeteredUsageAction, number>;
}

// CORE is the recommended tier. This is the single place that decision is
// made — nothing else in the pricing UI should hardcode which plan is
// "popular".
const POPULAR_PLAN: PlanName = 'CORE';

function buildPlanCard(plan: PlanName): PlanCard {
  const limits = PLAN_LIMITS[plan];
  if (!isPaidPlan(plan)) {
    return {
      plan,
      isPaid: false,
      priceLabel: formatInr(0),
      listPriceLabel: null,
      badge: null,
      accessDays: null,
      limits,
    };
  }
  const paidPlan = plan as PaidPlan;
  return {
    plan,
    isPaid: true,
    priceLabel: formatInr(launchAmountFor(paidPlan)),
    listPriceLabel: formatInr(listAmountFor(paidPlan)),
    badge: plan === POPULAR_PLAN ? 'Most popular' : null,
    accessDays: PLAN_ACCESS_DAYS_DEFAULT,
    limits,
  };
}

// Ordered FREE -> CORE -> MAX for card/table rendering, derived from
// PLAN_NAMES rather than a separately maintained literal array.
export const PRICING_PLANS: readonly PlanCard[] = PLAN_NAMES.map(buildPlanCard);

export function getPlanCard(plan: PlanName): PlanCard {
  const card = PRICING_PLANS.find((entry) => entry.plan === plan);
  if (!card) throw new Error(`Unknown plan: ${plan}`);
  return card;
}

// Human labels for each metered action, used as comparison-table row
// headers. This is presentation copy only — it does not change which
// actions are metered (that remains USAGE_ACTION_TYPES) or their limits.
const ACTION_LABELS: Record<MeteredUsageAction, string> = {
  CHAT: 'Chat answers',
  INGESTION: 'Sources ingested',
  AI_ACTION: 'AI Actions',
  SKILL_INTELLIGENCE: 'Skill Intelligence analyses',
  LEARNING_PATH: 'Learning Paths',
};

export interface LimitComparisonRow {
  kind: 'limit';
  action: MeteredUsageAction;
  label: string;
  values: Record<PlanName, number>;
}

export interface CapabilityComparisonRow {
  kind: 'capability';
  label: string;
  // Every capability row is available on every plan — the audit confirmed
  // Lumora does not gate any feature by plan today. `values: 'all'` makes
  // that an explicit, honest statement instead of implying differentiation
  // that doesn't exist in the code.
  values: 'all';
}

export type ComparisonRow = LimitComparisonRow | CapabilityComparisonRow;

// "What changes with your plan" — the five real, enforced differences,
// generated by mapping the metering config so a new metered action
// automatically gets a row.
export const LIMIT_COMPARISON_ROWS: readonly LimitComparisonRow[] = USAGE_ACTION_TYPES.map(
  (action) => ({
    kind: 'limit' as const,
    action,
    label: ACTION_LABELS[action],
    values: PLAN_NAMES.reduce(
      (acc, plan) => {
        acc[plan] = PLAN_LIMITS[plan][action];
        return acc;
      },
      {} as Record<PlanName, number>,
    ),
  }),
);

// "What every plan includes" — capabilities verified against the codebase
// to be identical across FREE/CORE/MAX. Do not add a row here without
// confirming there is no plan check gating it.
export const SHARED_CAPABILITY_ROWS: readonly CapabilityComparisonRow[] = [
  { kind: 'capability', label: 'PDF ingestion', values: 'all' },
  { kind: 'capability', label: 'Website ingestion', values: 'all' },
  { kind: 'capability', label: 'YouTube ingestion', values: 'all' },
  { kind: 'capability', label: 'Text and VTT ingestion', values: 'all' },
  { kind: 'capability', label: 'General knowledge chat', values: 'all' },
  { kind: 'capability', label: 'Grounded Workspace chat', values: 'all' },
  { kind: 'capability', label: 'Source citations with provenance', values: 'all' },
  { kind: 'capability', label: 'Streaming answers', values: 'all' },
  { kind: 'capability', label: 'Private, isolated Workspaces', values: 'all' },
  { kind: 'capability', label: 'Unlimited Workspaces', values: 'all' },
  { kind: 'capability', label: 'All AI Actions (Summarize, Explain, Compare, Generate Notes, Key Takeaways)', values: 'all' },
  { kind: 'capability', label: 'Resource Intelligence', values: 'all' },
  { kind: 'capability', label: 'Skill Intelligence / role gap analysis', values: 'all' },
  { kind: 'capability', label: 'Gap-to-Learning plans', values: 'all' },
  { kind: 'capability', label: 'Career Readiness report', values: 'all' },
];

export const COMPARISON_ROWS: readonly ComparisonRow[] = [
  ...LIMIT_COMPARISON_ROWS,
  ...SHARED_CAPABILITY_ROWS,
];

// Explanatory header for the shared-capability block — states honestly
// that plans differ in capacity, not in what you can do.
export const SHARED_CAPABILITY_HEADER =
  'Every Lumora capability is available on every plan. Paid plans raise how much you can do in each ' +
  `${USAGE_WINDOW_HOURS}-hour window.`;
