import type { Gap } from '../skills/types';
import type { RequiredCompetency } from './types';

function technicalSteps(gap: Gap, competency: RequiredCompetency): string[] {
  const subject = gap.subject;
  const observed = competency.observedLevel;
  if (observed === 'NONE') {
    return [
      `Learn the fundamentals of ${subject}.`,
      `Apply ${subject} inside a small, scoped exercise.`,
      `Use ${subject} end-to-end in a real project.`,
    ];
  }
  if (observed === 'MENTIONED') {
    return [
      `Move ${subject} from familiarity to hands-on practice.`,
      `Apply ${subject} directly inside a real project.`,
    ];
  }
  return [`Take a project that already uses ${subject} to a deployed, shipped state.`];
}

function projectArchetypeSteps(gap: Gap): string[] {
  return [
    `Scope a project that demonstrates ${gap.subject}.`,
    'Build and deploy the project end-to-end.',
    'Publish it with a working link or repository.',
  ];
}

function claimedSkillSteps(gap: Gap): string[] {
  return [
    `Pick one project where ${gap.subject} can be central.`,
    `Apply ${gap.subject} directly in that project's implementation.`,
  ];
}

function interviewPrepSteps(gap: Gap): string[] {
  return [
    `Study the core concepts behind ${gap.subject}.`,
    `Practice explaining ${gap.subject} out loud or in a mock interview.`,
  ];
}

export function isClaimedSkillGap(gap: Gap): boolean {
  return gap.ruleId === 'PROJECT_EVIDENCE' && gap.id.includes(':project:claimed:');
}

// Ordered, deterministic closure steps keyed only by ruleId and the gap's
// own observed-level shortfall — never generated by a model.
export function buildClosurePlan(gap: Gap, competency: RequiredCompetency): string[] {
  if (gap.ruleId === 'TECHNICAL_SKILL') return technicalSteps(gap, competency);
  if (gap.ruleId === 'PROJECT_EVIDENCE') {
    return isClaimedSkillGap(gap) ? claimedSkillSteps(gap) : projectArchetypeSteps(gap);
  }
  return interviewPrepSteps(gap);
}
